---
#topic(s) to check for to know whether sensor is in bag
sensors:
  #should this be camera or multisense
  multisense:
    - '/multisense/right/image_rect'
    - '/multisense/left/image_rect'
  velodyne_1:
    - '/velodyne_1/velodyne_points'
  velodyne_2:
    - '/velodyne_2/velodyne_points'
  novatel:
    - '/odometry/filtered_odom'
    - '/novatel/imu/data'
  racepak:
    - '/racepak/shock_pos'
    - '/racepak/wheel_rpm'
  thermal_left:
    - '/thermal_left/image'
  thermal_right:
    - '/thermal_right/image'
algz:
  # lidar_mapping:
  #   - '/local_gridmap'
  super_odometry:
    - '/superodometry/integrated_to_init'
  # lidar_stitching:
    # - '/full_cloud'
  roughness_cost:
    - '/traversability_cost'
  # tartanvo:
    # - '/tartanvo_odom'

intervention_topic: '/mux/intervention'
# speed_topic: '/odometry/filtered_odom'
gps_topic: '/odometry/filtered_odom'

keywords:
  context:
    - collect
    - test
    - learning_physics
    - sara
  condition:
    - sunny
    - snowy
    - muddy
