---
algorithms:
  irl: 'irl_node' #not actually what these are called
  mppi: 'mppi_node'
  super_odometry: 'super_odometry_node'
  lidar_mapping: 'atv_lidar_mapping'
#topic(s) to check for to know whether sensor is in bag
sensors:
  #should this be camera or multisense
  multisense:
    - '/multisense/right/image_rect'
    - '/multisense/left/image_rect'
  velodyne_1:
    - '/velodyne_1/velodyne_points'
  velodyne_2:
    - '/velodyne_2/velodyne_points'
  novatel:
    - '/asdfasdf'
intervention: '/mux/intervention'
keywords:
  context:
    - collect
    - test
    - learning_physics
    - sara
  condition:
    - sunny
    - snowy
    - muddy
