---
data_folder: '/home/yamaha/rosbags'
experiment_name: 'context_test'
pre:
  driver: Matthew
  robot: yamaha_viking
  launch:
    speed_adaptation:
      args:
    roughness_cost:
      args:

  other:
    live_notes:
    record:

  context:
  #keywords - collect, test, learning_physics, sara
    - 'testing'
    - 'SARA'
  conditions:
  #keywords - sunny, snow, muddy
    - 'sunny'
  course:
    - turnpike
