---
data_folder: '/home/physics_atv/rosbags'
experiment_name: 'dino_irl_pca'
pre:
  driver: Matthew
  robot: yamaha_viking
  launch:
    super_odometry:
      args:

    lidar_mapping_dino:
      args:

#    pointcloud_colorization:
#      args:

    dino_mapping:
      args: 
        visual_mapping_config: dino_vlad.yaml

    dino_irl:
      args:
        model_fp: ../models/yamaha/visual_ablations/2024-03-22-20-27-18_visual_ablations_vlad/itr_3.pt

    rviz:
      args:

  other:
      live_notes: 
#      record:

  context:
  #keywords - collect, test, learning_physics, sara
    - 'collect'
    - 'learning_physics'
  conditions:
  #keywords - sunny, snow, muddy
    - 'sunny'
  course:
    - 'green'
