---
data_folder: '/home/yamaha/rosbags'
experiment_name: 'integration_test'
pre:
  driver: Matthew
  robot: yamaha_viking
  launch:
    rviz:
      args:
    super_odometry:
        args:
    lidar_mapping:
      args:
    cvar_maxent_irl:
      args:
        obstacle_threshold: 0.0
    waypoint_manager:
        args:
    mppi:
      args:

#    sensors_all:
#      args:
#    super_odometry:
#      args:
#    lethal_height_costmapping:
#      args:
#        lethal_height: 0.3

  other:
    record:
    live_notes:

  context:
  #keywords - collect, test, learning_physics, sara
    - 'collect'
    - 'learning_physics'
  conditions:
  #keywords - sunny, snow, muddy
    - 'sunny'
  course:
    - 'green'
