---
data_folder: /home/yamaha/rosbags
experiment_name: tartandrive
pre:
  conditions:
  - afternoon
  - cloudy
  context:
  - collect
  course:
  - turnpike
  - figure_8
  - gupta
  - rough_rider
  driver: Sam
  launch: {}
  number_people: 2
  other:
    live_notes: null
    record: null
  robot: yamaha_viking
