---
data_folder: /home/physics_atv/rosbags
experiment_name: tartandrive
pre:
  conditions:
  - afternoon
  - sunny
  context:
  - collect
  course:
  - meadows
  - turnpike
  driver: Matthew
  launch: {}
  number_people: 2
  other:
    live_notes: null
    record: null
  robot: yamaha_viking
