---
data_folder: /home/yamaha/rosbags
experiment_name: tartandrive
pre:
  conditions:
  - afternoon
  - sunny
  - damp
  context:
  - collect
  course:
  - gupta
  driver: Sam
  launch:
    joystick_drive:
      args: null
  number_people: 2
  other:
    live_notes: null
    record: null
    topics_monitor: null
  robot: yamaha_viking
