---
data_folder: '/home/physics_atv/rosbags'
experiment_name: 'online_hdif'
pre:
  driver: Matthew
  robot: yamaha_viking
  launch:
    super_odometry:
        args:

#    pointcloud_colorization:
#        args:
    dino_mapping:
      args: 

    online_hdif:
      args:

    rviz:
      args:

  other:
      live_notes: 
      record:

  context:
  #keywords - collect, test, learning_physics, sara
    - 'collect'
    - 'learning_physics'
  conditions:
  #keywords - sunny, snow, muddy
    - 'sunny'
    - 'snow'
  course:
    - 'context'
