---
data_folder: '/home/physics_atv/rosbags'
experiment_name: 'online_hdif'
pre:
  driver: Sam
  robot: yamaha_viking
  launch:
    super_odometry:
        args:

    #pointcloud_colorization:
    #    arg:

    dino_mapping:
      args: 

    online_hdif:
      args:

    rviz:
      args:

    irl:
      args:

    lidar_mapping:
      args:

  other:
      live_notes: 
      record:

  context:
  #keywords - collect, test, learning_physics, sara
    - 'SARA'
    - 'Learning Physics'
  conditions:
  #keywords - sunny, snow, muddy
    - 'sunny'
  course:
    - 'green'
