---
data_folder: /home/yamaha/rosbags
experiment_name: parv_experiments
pre:
  driver: Matthew
  robot: yamaha_viking
  launch:
    rviz:
      args:
    super_odometry:
      args:
    lidar_mapping:
      args:
    lethal_height_costmapping:
      args:
#    cvar_maxent_irl:
#      args:
#        obstacle_threshold: 0.0
    mppi_throttle:
      args:
        node: 'mppi_throttle_tartan_50_all'
    waypoint_manager:
        args:
    real_time_vel:
      args:
    
  other:
    parv_record:
    live_notes:
    topics_monitor:
  context:
  #keywords - collect, test, learning_physics, sara
    - 'collect'
    - 'learning_physics'
  conditions:
  #keywords - sunny, snow, muddy
    - 'sunny'
  course:
    - 'green'
