---
data_folder: '/home/physics_atv/rosbags'
experiment_name: 'irl_postprocess'
pre:
  driver: Matthew
  robot: yamaha_viking
  launch:
    super_odometry:
      args:

    lidar_mapping:
      args:

    pointcloud_colorization:
      args:

    rviz:
      args:

  other:
    record:
    live_notes:

  context:
  #keywords - collect, test, learning_physics, sara
    - 'collect'
    - 'learning_physics'
  conditions:
  #keywords - sunny, snow, muddy
    - 'sunny'
  course:
    - 'green'
