---
data_folder: '/home/yamaha/rosbags'
experiment_name: 'launch_test'
pre:
  driver: Matthew
  robot: yamaha_viking
  launch:
    rviz:
      args:
    # super_odometry:
    #   args:
    # lidar_mapping:
    #   args:
    # lethal_height_costmapping:
    #   args:
    #     lethal_height: 0.3
    # mppi:
    #   args:
  other:
    # record:
    live_notes:
    topics_monitor:

  context:
  #keywords - collect, test, learning_physics, sara
    - 'collect'
    - 'learning_physics'
  conditions:
  #keywords - sunny, snow, muddy
    - 'sunny'
  course:
    - 'green'
